version: '3'
services:
  api:
    build: .
    image: event-planner-api:latest
    ports:
      - "8000:8000"
    env_file:
      - .env.prod
    depends_on:
      - database

  database:
    image: mongo:5.0.15
    ports:
      - "27017:27017"
    volumes:
      - data:/data/db

volumes:
  data: